### ISSUE TITLE
adding support for INCRBYFLOAT (DefaultClient)

### ISSUE THREAD

**Issue by maheshgawali** [jazzband/django-redis#311]
For a project I am working on we need to use [INCRBYFLOAT](https://redis.io/commands/incrbyfloat) 
I have already added the support for it in my [fork](https://github.com/maheshgawali/django-redis/tree/incr_float_change_to_ingore_check)

@niwinz : Please let me know your thoughts on adding support for INCRBYFLOAT, I can submit a PR immediately.

**Comment by niwinz** [comment]
Hmm is ok to add it, but i think we should not add more and more methods to the client, i think the `incr` should be enough for handle this also, adding an additional parameter. If it is ok that for you, PR is welcome ;)

**Comment by maheshgawali** [comment]
Since `INCRBYFLOAT` is a different method in the low level redis client (and redis documentation as well), I wanted to keep it analogous. So when anyone wants to use it they can identify it easily. Enabling behaviour of `INCRBYFLOAT` from `INCR` might be confusing.

**Comment by niwinz** [comment]
As I said before, django-redis is not a redis client, is a django cache backend. It should implement the interface of django cache backend. If you want access to redis funcionality you can access to redis connection directly using http://niwinz.github.io/django-redis/latest/#_raw_client_access that already exposes all redis functionality and we dont need reimplement it.

**Comment by WisdomPill** [comment]
I agree with @niwinz seems like your application is looking for something more than plain django cache backend is built for. I know it is two years you opened the issue, but I suggest to subclass `DefaultClient` and implement `INCRBYFLOAT` mimicking `INCRBY` call.

I am closing the issue, since the PR for adding `INCRBYFLOAT` was rejected.

**Comment by maheshgawali** [comment]
sure, thanks.
