### ISSUE TITLE
Latest version no longer compatible with mockredis?

### ISSUE THREAD

**Issue by Tecktron** [jazzband/django-redis#320]
Hello,
As Fakeredis seems to be out, I switched to the suggested mockredis, which seems to also be having issue, in the latest pypi version I'm getting this error:
```
    @property
    def client(self):
        """
            Lazy client connection property.
            """
        if self._client is None:
>           self._client = self._client_cls(self._server, self._params, self)
E           TypeError: mock_redis_client() takes 0 positional arguments but 3 were given

.tox/py36/lib/python3.6/site-packages/django_redis/cache.py:62: TypeError
```
IDK exactly how recent this is and maybe this is known or maybe I'm missing something or maybe the better option is to just switch to using either local memory or dummy for testing... thoughts on this appreciated.

As a side note I'd also like to point out that the documentation probably needs updating: 
http://niwinz.github.io/django-redis/latest/#_pluggable_redis_client
Looks like `"REDIS_CLIENT_CLASS"` has been changed to just `"CLIENT_CLASS"`

Cheers!

**Comment by Karmenzind** [comment]
Hi  @Tecktron 
Have you found a solution?

**Comment by Tecktron** [comment]
Nope, never did. I just ended up using the django dummy cache instead:
`'backend': 'django.core.cache.backends.dummy.DummyCache'`

**Comment by Karmenzind** [comment]
Thank you. But my project has already relied on django_redis's backend...

**Comment by Tecktron** [comment]
I just overwrote the settings for testing, if you're using the django's standard calls, it worked out fine.

**Comment by Karmenzind** [comment]
@Tecktron  
Can you show me your settings?
This is what I met https://github.com/niwinz/django-redis/issues/338

**Comment by Tecktron** [comment]
test_settings.py ```CACHES = {
    "default": {
        "BACKEND": 'django.core.cache.backends.dummy.DummyCache',
    },
}``` 
As long as you're not doing anything low level and using the standard Django calls, this works fine.

**Comment by Karmenzind** [comment]
I've tried this, but no luck. Because I've been using django_redis as the backend in our project and it has some particular functions (like `cache.delete_pattern`) that other backends just don't support. At now there's no way to just ditch the django_redis backend.
Still thank you.:smile:

**Comment by Karmenzind** [comment]
I'll see if I can refactor the parts using those special functions and try your advice again.

**Comment by Tecktron** [comment]
This is really more of a work around than a real solution. Since you're using this package's low level api, it's not really going to be very helpful. I was in a similar position and ended up refactoring. 

I consider this is to still be an open issue with django-redis using mockredis,  which is why I haven't closed it.

If you end up getting a real solution, I'd appreciate it if you could add them here as well. Sorry, I do wish I had a better answer than "refactor and work around it" for you. 

Cheers

**Comment by Karmenzind** [comment]
That's ok. I've solved https://github.com/niwinz/django-redis/issues/338 by correting the settings. 
I don't really need mockredis, so I cannot help you with the solution to this issue for now. Thanks a lot and good luck.

**Comment by adamchainz** [comment]
Fakeredis is well maintained now so I think this issue can be closed.

**Comment by jdufresne** [comment]
Thanks Adam.
