### ISSUE TITLE
incr do its job but nothing returns by get

### ISSUE THREAD

**Issue by rz-abs-shi** [jazzband/django-redis#330]
Hi,
In our server which are using of `django-redis==4.8.0`, for some keys (about 70%) when we use `cache.incr(key, 1)` it do its job successfully with no exception. But when we want to get it by `cache.get(key)` it returns `None`. This behavior faced us with a lot of problems,
Our package versions:
```
Django==1.11.2
django-redis==4.8.0
redis==2.10.5
```
I recently found out the issue because of timeout. When a key is timed out, `get` will return `None`, but `incr` do its job.

**Comment by niwinz** [comment]
Very strange, because we hace tests for this and this package is used in production in many installations. That behavior is very strange, can you provide a isolated testcase for reproduce the bug?

**Comment by WisdomPill** [comment]
Ping @rz-abs-shi 

Please reply to this issue otherwise it will be closed since it is old and as @niwinz said there are test covering this behavior like [here](https://github.com/jazzband/django-redis/blob/a6eb7692c7c686fc49c1329be1d078c4300f721b/tests/test_backend.py#L386)
