### ISSUE TITLE
adopt pexpire, pttl to align accuracy of set operation

### ISSUE THREAD

**Issue by andytzeng** [jazzband/django-redis#333]
To whom might concern this case,

I found the `set` API adopting ms in specifying expiration of redis `set()`. Therefore, the caller can use millisecond to expire the cache, just like
```
cache.set('key', 'value', timeout=1.5)
```

But, the `expire` and `ttl` API did not align the accuracy. Will we consider aligning the accuracy?

Thank you.

**Comment by niwinz** [comment]
If this is backward compatible, and does not have additional race conditions, is welcome ;)

**Comment by WisdomPill** [comment]
Hello @andytzeng!

Are you still considering to propose a PR to fix this issue?

As of my understanding `.expire()` and `.ttl()` do not support sub second representation,
using `PEXPIRE` and `PTTL` and divide the result by 1000 should do the trick.

Am I right?

If that is the case, I think it should be very easy to implement and test.
