### ISSUE TITLE
Expireat support

### ISSUE THREAD

**Issue by cashaev** [jazzband/django-redis#360]
Dear team!

Support for EXPIREAT command would be much appreciated!

**Comment by WisdomPill** [comment]
Hello @cashaev!

I think it is quite easy to implement, do you fancy giving it a shot and open a PR?

**Comment by cashaev** [comment]
> Hello @cashaev!
> 
> I think it is quite easy to implement, do you fancy giving it a shot and open a PR?

Hi, @WisdomPill !
Thank you for the offer. Though it is quite late, but I will take a chance and contribute with pleasure.

Please, check the PR [https://github.com/jazzband/django-redis/pull/472](url)

**Comment by WisdomPill** [comment]
Thanks for the contribution @cashaev !
