### ISSUE TITLE
Support for version 5.X of Redis Engine

### ISSUE THREAD

**Issue by HewittJC** [jazzband/django-redis#364]
When using this to connect to our Redis instance out in ElastiCache we ran into the issue where it would not connect to Redis Engine 5.0 and we had to downgrade the Redis Engine to 2.8.X.

Is support for newer engine versions something that is on the horizon?

**Comment by niwinz** [comment]
This is something that depends on the underlying redis client. Not in django-redis it self that uses a very limited set of api.

**Comment by sevdog** [comment]
I am using this with Redis `5.0.5`, if the client library supports it there is no problem. In my case:
```
hiredis==1.0.0
redis==2.10.6
```

**Comment by jdufresne** [comment]
I believe this has by solved upstream by redis-py. If you continue to experience issues, please report the full details.
