### ISSUE TITLE
Default client does not handle string value for timeout

### ISSUE THREAD

**Issue by engstrom** [jazzband/django-redis#377]
I was hunting down the cause of a `ResponseError` with django_redis and after a lot of searching I found that my timeout value was being passed in as a string (my fault).

I traced the issue down to [this line](https://github.com/niwinz/django-redis/blob/302359554427c7b7f36380aa9f0ce20dea906879/django_redis/client/default.py#L130). If the timeout value received is a string like `'3'` then the timeout is set to one-thousand threes instead of 3000. e.g. `333333333333333333333333333333...`

The traceback looks like this:
```python
Traceback (most recent call last):
  File "/Users/engstrom/code/django-redis/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/Users/engstrom/code/django-redis/django_redis/cache.py", line 67, in set
    return self.client.set(*args, **kwargs)
  File "/Users/engstrom/code/django-redis/django_redis/client/default.py", line 150, in set
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ResponseError: value is not an integer or out of range
```

The message is pretty obvious now that I know the cause but it took me longer than I'd like to admit to realize that initially. Anyway, I thought it might be worth handling this case to save someone else time in the future.

**Comment by danidee10** [comment]
I'm having the same Issue too. Lol

**Comment by niwinz** [comment]
Seems like is an aplication bug, the timeout is always expected be an number. Or I'm missing something?

**Comment by danidee10** [comment]
Yeah but perhaps the error message can be clearer?. Maybe raise a `TypeError` instead of a `ConnectionInterrupted` Exception

**Comment by jdufresne** [comment]
IMO, this is an application bug and the library shouldn't add type checks to low level methods.

Support for adding mypy type checking support would be welcome though: #428
