### ISSUE TITLE
Create key in _incr method with timeout

### ISSUE THREAD

**Issue by jadhavmanoj** [jazzband/django-redis#379]
Currently, _incr function if key is not available it will create with no timeout.

I feel incr_() should create key with expiry given in incr method.

In my use case I increment counter in **async** using celery & rabbitmq, in such scenario there is chances of losing data as key is not set if multiple process call same function at a time.

Can anyone suggest good practice to fix this issue? or I will create PR for the same.

**Comment by jezdez** [comment]
@jadhavmanoj I'm not sure why you tagged me in this issue, but I'm not the author of this library.

**Comment by jadhavmanoj** [comment]
> @jadhavmanoj I'm not sure why you tagged me in this issue, but I'm not the author of this library.

Sorry, It happen because of typo or something. Removed you from tag.

**Comment by WisdomPill** [comment]
Hello @jadhavmanoj!

Can you come up with a PR to fix this?

**Comment by MostafaTaheri** [comment]
@jadhavmanoj I think the below solution will be suit you:

1- You need to have a function to generate a redis key based on each process (now you do not lose the data of each process.)

2- Set a default time for expiry if the input parameter was none.

**Comment by WisdomPill** [comment]
@jadhavmanoj reading again your issue it seems to me you need to have locking mechanism which is supported through `cache.lock("lock_name")` and actually uses redis lock. Feel free to reopen if you have other considerations or I did not answer your question
