### ISSUE TITLE
How to keep the redis cache consistent with mysql data?

### ISSUE THREAD

**Issue by Abeautifulsnow** [jazzband/django-redis#380]
When I updated the data of mysql dabatase, the redis cache was not updated in time. What should I do to make mysql data change, redis can also clear the old cache in time? Do i need to do some setting?

**Comment by adamrt** [comment]
This is the point of a cache. It doesn't have to hit the database and serves the data from memory.

You can read up on the Django Cache Framework documentation here: https://docs.djangoproject.com/en/2.2/topics/cache/

You can have your Model.save() method update the cache or you can have the cache invalidated by a time out and a couple more options. The option depends on your use case.
