### ISSUE TITLE
iter_keys() ignore KEY_FUNCTION

### ISSUE THREAD

**Issue by lionel126** [jazzband/django-redis#382]
tail of traceback :

> ...\django_redis\util.py", line 40, in default_reverse_key
>  return key.split(':', 2)[2]

it occurs when I define KEY_FUNCTION, ignoring argument **version**, like

> def get_key_ignore_version(key, key_prefix, version):

>   return key_prefix + ':' + key

**Comment by WisdomPill** [comment]
Hello @lionel126!

Sorry for the late response, can you provide a code sample?

**Comment by WisdomPill** [comment]
Closing this because there was no response and it is a year old
