### ISSUE TITLE
How do I do an atomic incr() if the key is not set?

### ISSUE THREAD

**Issue by dennisai** [jazzband/django-redis#4]
If I perform an incr(key) where the key is not already set, the incr() should set the key to 1.  However, the default behavior in Django's get_cache function does not allow you to do this.  Is there a way to drop down to the redis-py client that allows you to do this atomic incr?

**Comment by maheshgawali** [comment]
I am facing this issue as well, but for the `DefaultClient` . I can submit a PR for it. Please let me know if such a feature is good to have or not @niwinz 

I have a usecase where `incr` is intended to be done by mulitple processes and using `set` (to init keys) poses a risk of multiple processes NOT finding the key and then setting it to a default value and then incrementing.

```python
value = redis_conn.get(redis_key)
if value:
    redis_conn.incr(redis_key, delta=count)
else:
    redis_conn.set(redis_key, delta=count, timeout=PREDECIDED_TIMEOUT)
```

what I want is:
```python
redis_conn.incr(redis_key, delta=count)
redis_conn.expire(redis_key, timeout=PREDECIDED_TIMEOUT)
```

I have already forked and modified the code which works for me.

@niwinz : thanks for this great lib, it has been lot of help over the years.

**Comment by niwinz** [comment]
@maheshgawali if you have an improvement, please, submit it and we'll discus then over the code :D 
if it make sense I'll gladly merge it \o/
