### ISSUE TITLE
New maintainer needed.

### ISSUE THREAD

**Issue by niwinz** [jazzband/django-redis#400]
Hi,

Unfortunatelly or not i'm no longer using python on my daily job and right now i dont have time to maintain this package. So for not just abandon it, i'm looking for a new maintainer.

**Comment by jdufresne** [comment]
Hi @niwinz I've contributed to the project over the years and would be happy to lend a hand.

One option would be to pass the project to [Jazzband](https://jazzband.co). Jazzband is a collaborative community to share the responsibility of maintaining Python-based projects. They host and develop many different Python & django projects. See here for a full list: https://github.com/jazzband/

If the above is agreeable, I'm happy to contact Jazzband to begin the process. Using Jazzband would allow you to resume contributing should you ever choose to in the future.

WDYT?

**Comment by niwinz** [comment]
@jdufresne Thank you very much for taking the step forward. I was thinking of writing to you in private, you were the first person I thought of ...

jazzband looks awesome, so please, go forward for start the process. Meanwhile, if you need something, just ping (mentioning me)

**Comment by mrbaboon** [comment]
:+1: for passing this to Jazzband!

**Comment by terencehonles** [comment]
@jdufresne / @niwinz any chance we can get some eyes on Django 3.0 compatibility. I created #401 and there was a pre-existing #394. I created #401 because I don't think we should add `six` as a dependency, but instead drop it for Django 3.x which implies Python 3.x.

I'd also like to investigate Python 3.8 support (the library may work as is), but the nearer term change for work is Django 3.0.

**Comment by terencehonles** [comment]
I'll also add that I'm willing to help maintain the project because my work uses it, and I can justify helping maintain it. However, as suggested, Jazzband may be the best direction for the project.

**Comment by jdufresne** [comment]
I opened a ticket with Jazzband to begin the move process: https://github.com/jazzband-roadies/help/issues/176

**Comment by jdufresne** [comment]
Also of note, there is discussion among Django developers as to how to handle Redis in Django core: https://groups.google.com/d/msg/django-developers/38nas-aMbRw/FoSsickfBQAJ

**Comment by auvipy** [comment]
moving to Django core would be awesome

**Comment by codingjoe** [comment]
Yes, Django core support would be great but a lengthy process and will mean this package would vanish. For now, I would be in favor of JazzBand. @niwinz if you prefer a person over the JazzBand, I am happy to maintain the package in the future. I have plenty projects using redis not only for cashing but locks and other things. So I have an elevated interested in maintaining this package. I would also move it to our organization. Therefore, it would have a corporate sponsor, if that's what you are looking for.

**Comment by JBKahn** [comment]
Does anyone else have access right now to merge/publish/manage? I'm hoping to get a copy of master on pypi.

**Comment by niwinz** [comment]
@jdufresne right now has practically all access to github.
I have pending task to transfer this repo to the jazzband organization.
And @jdufresne tellme your pypi user for provide you permissions for publish the package.

**Comment by jdufresne** [comment]
My PyPI username is `jdufresne` :slightly_smiling_face: Thanks.

**Comment by jdufresne** [comment]
Version 4.11.0 was just released with Django 3.0 support.

**Comment by JBKahn** [comment]
Thanks @niwinz and @jdufresne

**Comment by ramwin** [comment]
Thanks @niwinz and @jdufresne

**Comment by thor** [comment]
A little follow-up here: would you guys like to, perhaps @niwinz if it has to be the owner, follow up on https://github.com/jazzband-roadies/help/issues/176#issuecomment-562698109? :sun_with_face:

**Comment by jdufresne** [comment]
The project has moved to jazzband.
