### ISSUE TITLE
Missing support for thread_local param.

### ISSUE THREAD

**Issue by MasterElrond** [jazzband/django-redis#427]
As mentioned in a [pull request](https://github.com/niwinz/django-redis/pull/393), this package is missing support for the `thread_local` keyword in the `lock` method of the `DefaultClient` and `ShardClient`.

Trivial fix, add `**options**` to both methods:

```
    def lock(self, key, version=None, timeout=None, sleep=0.1,
             blocking_timeout=None, client=None, **options):
        if client is None:
            client = self.get_client(write=True)

        key = self.make_key(key, version=version)
        return client.lock(key, timeout=timeout, sleep=sleep,
                           blocking_timeout=blocking_timeout, **options)
```

I'd recommend adding `**options**` over adding a new keyword because it will reduce overhead and has no downside, since `Redis.lock` will throw a `TypeError` if someone tries to submit invalid option.

**Comment by jdufresne** [comment]
Merged in ebfad38cbe5cb69abcbc036f087d6122228e3591
