### ISSUE TITLE
Add and support type hints

### ISSUE THREAD

**Issue by asfaltboy** [jazzband/django-redis#428]
We can use something like mypy to validate for type errors during a CI build. And the same types can be exposed to any code that uses django-redis as a dependency.

Django-redis should be able to support it with native syntax: https://docs.python.org/3/library/typing.html since the supported python versions start at 3.5

How do you feel about this @niwinz ? If you're interested, I can bootstrap this effort in a PR and we can discuss the changes there.

**Comment by jdufresne** [comment]
That is a welcome improvement. If you put up a PR, I'll take a look.

**Comment by WisdomPill** [comment]
Hello, I just joined jazz band and I would love to start contributing maybe right from the support for typing. I will submit a PR in a short time with some type hints
