### ISSUE TITLE
Documentation site is not available 

### ISSUE THREAD

**Issue by FaizanFareed** [jazzband/django-redis#433]
When i hit this link 404 page is showing 
[http://niwinz.github.io/django-redis/latest/](url)
@jdufresne

**Comment by garrypolley** [comment]
There is a version, I think it's missing styles, that can be seen here: https://jazzband.github.io/django-redis/latest/

**Comment by jdufresne** [comment]
We're in the process of moving django-redis to the Jazzband organization. Once complete, the documentation will be re-available. Thanks for the patience during the transition. I'll post back here once more progress has been made.

**Comment by FaizanFareed** [comment]
@garrypolley and @jdufresne  thanks for informing !

**Comment by amureki** [comment]
Greetings,

I made a PR fixing this issue: #436 
Would be happy to get a review there!

Regarding the styling: there were no CSS before, plain text. :)
We might consider moving the whole thing to http://readthedocs.io/ but I guess, my PR is fine as a quick win.

Best,
Rust
