### ISSUE TITLE
How to enable SSL 

### ISSUE THREAD

**Issue by Aletz-Arce** [jazzband/django-redis#437]
Hi, i try to use django-redis backend with Redis database hosted in Digital Ocean.
A requirement for connection is ``--tls`` flag, that's mean client will be connect with ssl enabled.
I don't figure how to set ssl parameter in *CACHE* setting parametet, this is my current setting, with that server always close connection.

`CACHES = {
   'default': {
       'BACKEND': 'django_redis.cache.RedisCache',
       'LOCATION': 'redis://default:XXXX@private-redis-XXXX.db.ondigitalocean.com:25061',
       'OPTIONS': {
           'DB': 0,
           # 'PASSWORD': 'XXXX',
           'PICKLE_VERSION': -1,
           "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
           "REDIS_CLIENT_KWARGS": {"ssl": True},
       },
   },
}`

**Comment by ezubillaga** [comment]
Try modifying the connection's DSN from 'redis://...' to 'rediss://...' (please note the extra 's'). I haven't tested myself but I believe it should work.

**Comment by Aletz-Arce** [comment]
> Try modifying the connection's DSN from 'redis://...' to 'rediss://...' (please note the extra 's'). I haven't tested myself but I believe it should work.

Thanks @ezubillaga  that´s right, using DSN prefixed with ``rediss`` do the work.

**Comment by karthiknarayan07** [comment]
thanks man , i wasted 1 day figuring that out 😑


> Try modifying the connection's DSN from 'redis://...' to 'rediss://...' (please note the extra 's'). I haven't tested myself but I believe it should work.
