### ISSUE TITLE
Doc link is unavailable

### ISSUE THREAD

**Issue by michael-yin** [jazzband/django-redis#438]
The doc link on the homepage of this project http://niwinz.github.io/django-redis/latest/ seems not working.

I got 404 error from Github.

Hope the maintainer can put the doc to readthedocs.

Thx.

**Comment by jdufresne** [comment]
We're in the process of moving django-redis to the Jazzband organization. Once complete, the documentation will be re-available. Thanks for the patience during the transition. I'll post back here once more progress has been made.

**Comment by WisdomPill** [comment]
Docs have moved to http://jazzband.github.io/django-redis/latest/ but there is an issue with styling, there is some link to https://niwi.nz/_assets/asciidoctor-styles/simple-red-titles/stylesheet.css that clearly does not exist anymore.

Furthermore the website in the description still points to the old docs.

@jdufresne can you help on fixing these two issues?

**Comment by jdufresne** [comment]
Resovled in d1f529615313a3da72cb9e6dd302b2741ee1b43b

Thanks for the report. Please let me know if you experience any new issues with the docs.

**Comment by WisdomPill** [comment]
Still the description of the repository points to the old docs

There is http://niwinz.github.io/django-redis/latest/ in the description

**Comment by jdufresne** [comment]
> Still the description of the repository points to the old docs

I don't have permission to edit this.

@jezdez Are you able to edit the GitHub project description to remove the old docs link?

![django-redis](https://user-images.githubusercontent.com/347634/84596430-8c9d8800-ae12-11ea-936d-f463db9df75b.png)

**Comment by jezdez** [comment]
Removed the link!

**Comment by jdufresne** [comment]
Thanks!

**Comment by OJFord** [comment]
PyPI points to http://jazzband.github.io/django-redis/latest/ also mentioned as the new place by  @WisdomPill above, but 404s. (So does jazzband.github.io entirely.)
