### ISSUE TITLE
Django 3 support release

### ISSUE THREAD

**Issue by tomhamiltonstubber** [jazzband/django-redis#453]
Hi folks,

Please can we get a release soon? Currently on master are the changes that fix the Deprecation Warning for using `smart_str` instead of `smart_text`, as well as quite a lot of other changes by the looks of things.

Happen to help, just point me towards something that needs done.

**Comment by jdufresne** [comment]
Thanks. 4.12 went out today: https://pypi.org/project/django-redis/4.12.1/

**Comment by tomhamiltonstubber** [comment]
amazing thanks
