### ISSUE TITLE
Infinite timeout and Redis TTL

### ISSUE THREAD

**Issue by plumdog** [jazzband/django-redis#459]
Does setting `timeout=None` set a TTL in Redis at all? Redis handles things with and without TTLs differently when trying to free up memory, namely that (using what I think is the default maxmemory-policy, `volatile-lru`) keys without a TTL are not considered for eviction, but keys with a TTL are considered for eviction. See https://redis.io/topics/lru-cache#eviction-policies. This means that setting `timeout=None`

Is there a way of saying "set a TTL in Redis that is _forever_" vs "don't set the TTL in Redis"?

I think that the terminology "infinite timeout" doesn't make it clear which of these happens, and therefore which behaviour to expect from Redis when it starts running out of memory.

From what I can tell, Redis doesn't have the concept "TTL is set, but is _forever_", so it might be the closest to this I can get is to set `timeout=2**31-1` (which is ~25k days, which is ~68 years, which I'm happy to conclude is functionally forever).

**Comment by WisdomPill** [comment]
Hello @plumdog !

> Is there a way of saying "set a TTL in Redis that is forever" vs "don't set the TTL in Redis"?

There is not difference, if you set `timeout=None` the client will not set the `EX` parameter and that means that there will be no TTL and also means 'TTL forever' (the key will not be evicted using `volatile-lru`).

Did I answer your question?

**Comment by plumdog** [comment]
Yes.

That Redis doesn't differentiate does it clear and does make sense.

I do think that the terminology "infinite timeout" is a bit confusing, because it isn't clear how `volatile-lru` will handle them. From what I can tell (https://redis.io/commands/expire, https://redis.io/commands/ttl, https://redis.io/commands/persist) Redis' own documentation doesn't use "infinite timeout". Calling them "persistent keys" or "no timeout" or something might make this clearer.
