### ISSUE TITLE
Release page lists 4.5.0 as "latest release", not 4.12.1?

### ISSUE THREAD

**Issue by hartwork** [jazzband/django-redis#463]
Hi!

I'm a happy [user of django-redis](https://github.com/hartwork/jawanndenn/network/dependencies) — thanks for sharing it as software libre! :pray: 
I noticed the release page lists 4.5.0 of 2016 as "latest release" rather than 4.12.1 of 2020. Is that intended?

Thanks and best, Sebastian

**Comment by hartwork** [comment]
Any thoughts?

**Comment by jdufresne** [comment]
Thanks for the report. Fixed.
