### ISSUE TITLE
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django_redis.cache.RedisCache': Module "django_redis.cache" does not define a "RedisCache" attribute/class

### ISSUE THREAD

**Issue by golangav** [jazzband/django-redis#465]
python 3.6 
Django==2.1.15
django-redis==4.11.0
redis==3.3.11

启动报错：
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django_redis.cache.RedisCache': Module "django_redis.cache" does not define a "RedisCache" attribute/class
![image](https://user-images.githubusercontent.com/21213494/90477428-f6614780-e15d-11ea-95ab-fb6ac6a87975.png)

**Comment by golangav** [comment]
can you help I ?

**Comment by jdufresne** [comment]
Looks like an issue with your installation or your virtualenv. Cannot reproduce.

**Comment by golangav** [comment]
没问题啊

**Comment by golangav** [comment]
It's not about the environment. Other people have the same problem

**Comment by jdufresne** [comment]
Can you link to a minimal project that demonstrates the issue with djang-redis? If so, I'll happily dive in and take a look.

**Comment by deepanshumehtaa** [comment]
any update on this ?
