### ISSUE TITLE
Pass all the cache param to the actual redis client

### ISSUE THREAD

**Issue by dzanotelli** [jazzband/django-redis#469]
It would be nice if `django_redis.pool.ConnectionFactory` method `make_connection_params` (lno 29) can pass ALL the params to the acutal Redis client. Now it manages only 'PASSWORD', 'SOCKET_TIMEOUT', 'SOCKET_CONNECT_TIMEOUT'.
In upper case only.

My scenario:
- django-environ which reads `CACHE_URL` from a `.env` (text) file:
```
CACHE_URL=rediscache://localhost:6379/0?client_class=django_redis.client.DefaultClient&socket_connect_timeout=15&socket_timeout=5&socket_keepalive=True
```

- django `settings.py` with:
```
CACHES = {
    'default': env.cache(),
}
```
which generates the following dict:
```
{'default': {'BACKEND': 'django_redis.cache.RedisCache',
  'LOCATION': 'redis://localhost:6379/0',
  'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient',
   'SOCKET_CONNECT_TIMEOUT': 15,
   'SOCKET_TIMEOUT': 5,
   'SOCKET_KEEPALIVE': True}}}
```
you can see the options are all in upper case, even if in env are lower. But that's fine.

- inspecting the redis cache client:
```
from django.utils.cache import caches
c = caches['default']
r = c.client.get_client()
r
Out[31]: Redis<ConnectionPool<Connection<host=localhost,port=6379,db=0>>>
r.connection_pool.connection_kwargs
Out[32]: 
{'parser_class': redis.connection.PythonParser,
 'socket_connect_timeout': 15,
 'host': 'localhost',
 'port': 6379,
 'username': None,
 'password': None,
 'db': 0}
```

The `redis.client.Redis` wants the kw in lower case, and the `ConnectionFactory` correctly lowerizes them. But as you can see the `socket_keepalive` is missing.

Morevore, nor i can just set it in the settings like this (dirty workaround):
```
CACHES = {
    'default': env.cache(),
}

CACHES['default']['OPTIONS']['socket_keepalive'] = True
```
because the `make_connection_params` just ignores it.

Why just dont
1. lowerize all the keys in `self.options` (`ConnectionFactory`)
2. pass all of them to the redis client class when performing `connect` (method at lno 60)

If the system breaks, cos the user passes a wrong arg, it's actually a user problem: I think the `ConnectionFactory` class should not manage the given args in a so strict way.

**Comment by jdufresne** [comment]
Thanks for the thorough report :+1:  Are you interested in contributing a PR that to solve it?

**Comment by dzanotelli** [comment]
Yeah, why not, I guess is just a matter of few lines of code.

**Comment by dzanotelli** [comment]
@WisdomPill 
I went deep into the issue, and i figure out that the situation is a little more complex.

The complete workflow:
1. django-redis instantiate a `django_redis.cache.RedisCache` object
1. the `RedisCache.client` property instantiates a `django_redis.client.DefaultClient` (you can specify it in the CACHE OPTIONS, but it's also the default)
1. the `DefaultClient` calls a `connect` method, which calls the `django_redis.pool.get_connection_factory` function which returns by default a `django_redis.pool.ConnectionFactory` object.
1. the `ConnectionFactory` sets `redis.client.RedisClient` as default client class and `redis.connection.ConnectionPool` as default class to build a pool of connections (in short, in redis-py you are able to instantiate a `RedisClient` object passing all the connection defails or passing them to a `ConnectionPool` object which manages the sets of available connections for the client, and pass the `ConnectionPool` object to the `RedisClient`)
1. the `ConnectionFactory` object calls `connect` which manipulates our params calling the method `make_connection_params` (the params are the ones found in the `settings.CACHE['default']['OPTIONS]`, this is the point where our issue starts)
1. the `ConnectionFactory` object instantiates a `ConnectionPools` passing the params
1. the `ConnectionPools` uses by default the class `redis.connection.Connection` to build the connections: is this last one which finally gets our params.

We can't:
* just pass all the `settings.CACHE['default']['OPTIONS]` (initial idea), since they are taken by some class somewhere, and common args such as `CLIENT_CLASS` may be found in it and will break the workflow for sure (tested)
* inspect the client class and pass only the good args (my second idea, using the inspect module) because:
  - this work is done in the `ConnectionFactory` which knows the client class (`RedisClient`) but cannot reach directly the `Connection` class. Or at least, ye it's possible but also very tricky to do that: it's a chinese boxes mechanism where we rely on specific classes declared as defaults..
  - you may use no `ConnectionPool` (can we?) and in this case the args should be passed directly to the `RedisClient` which has a different signature from `Connection`.

As you can see, the situation is quite complex and i don't know the creator idea in building a such complex structure. There may be use cases (eg. passing custom client classes in args) which are now supported by the actual structure that I could break with my fixes (?).

Anyway, possible solutions are:
* keep the situation as is
* (manually) add missing params management inside `make_connection_params ` method just for the args which are both present in the `RedisClient` and `Connection` classes signatures. This still does not make the process 100% bug-free from future changes upstream in redis-py (but I guess, this is obvious and still a thing for everything in the package :)

Please let me know if doing solution 2 makes any sense to you: in that case I will submit my PR. Or if in the creator mind there are any other caveats I can't see right now, and you prefer to manage (or not) the thing by yourselves.

**Comment by WisdomPill** [comment]
I do not understand why you do not use `REDIS_CLIENT_KWARGS` and `CONNECTION_POOL_KWARGS`.

Furthermore I have tried myself setting `socket_keepalive = True` on the `REDIS_CLIENT_KWARGS` and I expected to find the options on the client by I did not.
Meanwhile setting the option on `CONNECTION_POOL_KWARGS` seem to work.

I have to dig into it, so I will be sure if your modifications are needed or not.

**Comment by dzanotelli** [comment]
Mmm actually this `CONNECTION_POOL_KWARGS` seems a good suggestion. Maybe it's my bad: i missed this param. I'll try it and let you know.

**Comment by dzanotelli** [comment]
Ok I checked it.
My problem is that my conf relies on django-environ with

.env file
```
CACHE_URL=rediscache://localhost:6379/0?client_class=django_redis.client.DefaultClient&socket_connect_timeout=5&...&socket_keepalive=False
```

settings.py
```
CACHES = {
    'default': env.cache(),
}
```
The url params in the `.env` file are all added to the `CACHES['default']['OPTIONS']`, level 1, and I couldnt find a way to write the url in order to have a nested dictionary with `CONNECTION_POOL_KWARGS` and its subkeys.

Indeed a workaround may be something like this, in `settings.py`:
```
CACHES = {
    'default': env.cache(),
}

CACHES['default']['OPTIONS']["CONNECTION_POOL_KWARGS"] = {
    "max_connections": 100,
    "retry_on_timeout": True,
    "socket_keepalive": True
}
```
and add more keys in the `.env` files to read the single sub-values.. not a splendid solution though.

Actually at this point i'm not sure if the issue deals with django-environ or your django-redis, I guess it's a case where the two things don't intersect 100% well (and maybe it's fine like this).

**Comment by WisdomPill** [comment]
I do not think it is a `django-redis`, 
if you disagree and have something in mind to fill the gap please consider proposing your idea and maybe a PR.

Otherwise I think we can just close the issue.

**Comment by dzanotelli** [comment]
Let's close the issue, if something new pops up, ill open a new one.
Thanks for your support.
