### ISSUE TITLE
Job failing on Travis-CI for Intel

### ISSUE THREAD

**Issue by kishorkunal-raj** [jazzband/django-redis#471]
Hi All,
I am trying to run the jobs on Travis CI and been observed that job for TOXENV=lint  on AMD64 if failing. Logs are mentioned below

$ python --version

Python 3.6.7

$ pip --version

pip 20.1.1 from /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip (python 3.6)
install

1.76s$ pip install tox

8.09s$ tox

lint create: /home/travis/build/kishorkunal-raj/django-redis/.tox/lint

lint installdeps: black, flake8, isort >= 5.0.2

lint installed: appdirs==1.4.4,black==20.8b1,click==7.1.2,dataclasses==0.7,flake8==3.8.4,importlib-metadata==2.0.0,isort==5.6.1,mccabe==0.6.1,mypy-extensions==0.4.3,pathspec==0.8.0,pycodestyle==2.6.0,pyflakes==2.2.0,regex==2020.9.27,toml==0.10.1,typed-ast==1.4.1,typing-extensions==3.7.4.3,zipp==3.3.0

lint run-test-pre: PYTHONHASHSEED='67920843'

lint run-test: commands[0] | black --target-version py35 --check --diff .

--- tests/test_backend.py	2020-10-09 12:29:27.773883 +0000

+++ tests/test_backend.py	2020-10-09 12:29:42.340158 +0000

@@ -321,17 +321,22 @@

         key = "key"

         value = "value"

 

         with patch.object(pipeline, "set") as mocked_set:

             self.cache.set(

-                key, value, client=pipeline,

+                key,

+                value,

+                client=pipeline,

             )

 

         if isinstance(self.cache.client, herd.HerdClient):

             default_timeout = self.cache.client._backend.default_timeout

             herd_timeout = (default_timeout + herd.CACHE_HERD_TIMEOUT) * 1000

-            herd_pack_value = self.cache.client._pack(value, default_timeout,)

+            herd_pack_value = self.cache.client._pack(

+                value,

+                default_timeout,

+            )

             mocked_set.assert_called_once_with(

                 self.cache.client.make_key(key, version=None),

                 self.cache.client.encode(herd_pack_value),

                 nx=False,

                 px=herd_timeout,

would reformat tests/test_backend.py

Oh no! 💥 💔 💥

1 file would be reformatted, 41 files would be left unchanged.

ERROR: InvocationError for command /home/travis/build/kishorkunal-raj/django-redis/.tox/lint/bin/black --target-version py35 --check --diff . (exited with code 1)

___________________________________ summary ____________________________________

ERROR:   lint: commands failed

The command "tox" exited with 1.
cache.2

store build cache

Done. Your build exited with 1.

Please look into it. 
Travis Job ID: https://travis-ci.com/github/kishorkunal-raj/django-redis/jobs/397394806

**Comment by cashaev** [comment]
Same thing happened for me here https://travis-ci.org/github/jazzband/django-redis/jobs/734378938
Looks like linter issue, when black is trying to reformat the file

**Comment by cashaev** [comment]
put arguments @ self.cache.set(...) and self.cache.client._pack(...) on separate lines as suggested by the linter.

**Comment by kishorkunal-raj** [comment]
I had tried putting the arguments in different lines as suggested in the logs, but still same issue persists and it does not made any difference. Below are the logs
with patch.object(pipeline, "set") as mocked_set:
             self.cache.set(
-                key, 
-                value, 
+                key,
+                value,
                 client=pipeline,
             )
         if isinstance(self.cache.client, herd.HerdClient):
             default_timeout = self.cache.client._backend.default_timeout
             herd_timeout = (default_timeout + herd.CACHE_HERD_TIMEOUT) * 1000
             herd_pack_value = self.cache.client._pack(
-                    value, 
-                    default_timeout,
-                    )
+                value,
+                default_timeout,
+            )

**Comment by WisdomPill** [comment]
Where did you see that? To me it seems that you are still looking at the same build of 3 days ago

**Comment by kishorkunal-raj** [comment]
JOB ID: https://travis-ci.com/github/kishorkunal-raj/django-redis/jobs/398250790

**Comment by WisdomPill** [comment]
I see, there is still an indentation problem, black does not like it.

By the way you can run black in order to fix these issues like the following `black .`

**Comment by cashaev** [comment]
check how it was done in my PR,
https://github.com/jazzband/django-redis/pull/472/files

**Comment by jdufresne** [comment]
This should be fixed with dbb90a2a127bf394972fb1aa4bfb7cabd03ced3f.
