### ISSUE TITLE
get_redis_connection hangs up if redis is down.

### ISSUE THREAD

**Issue by tucosaurus** [jazzband/django-redis#473]
Hey, Im trying to create a health check endpoint for my django and drf based application. Here's how Im checking it.

```
from django_redis import get_redis_connection

conn = get_redis_connection()
conn.ping()
```

This code works fine in the python shell. `conn.ping` raises a connection error if redis is down. However, when I request the endpoint and redis is down, the thread hangs forever. Here's my configuration for cache backend.

```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://localhost:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PARSER_CLASS": "redis.connection.HiredisParser",
            "CONNECTION_POOL_CLASS": "redis.BlockingConnectionPool",
            "CONNECTION_POOL_CLASS_KWARGS": {
                "max_connections": env.int("REDIS_MAX_CONNECTIONS", default=10),
                "timeout": 1,
            },
            "SOCKET_CONNECT_TIMEOUT": 1,  # seconds
            "SOCKET_TIMEOUT": 1,  # seconds
        },
    }
}
```

Could you help me out with why a Connection error is not being raised ? Also, please let me know if this query would be suitable elsewhere

**Comment by WisdomPill** [comment]
Hello @tucosaurus!

How do you ping redis without shell?
Are sure it does not throw another exception?
Furthermore are you sure that the options are passed to the client you are using?

**Comment by tucosaurus** [comment]
@WisdomPill Thank you for your response. 
I have a drf api view which pings redis. Im pretty sure it does not throw any exception. My server just hangs if redis is down. I will verify that the options are being passed to the client and get back to you.

**Comment by tucosaurus** [comment]
this was happening due to django rest frameworks throttling. Thank you for your time @WisdomPill
