### ISSUE TITLE
incr_version and decr_version delete keys with infinite timeout

### ISSUE THREAD

**Issue by z0ng33** [jazzband/django-redis#483]
When I try to incease or decrease version of some keys with infinite timeout, they just disappear.

After small research, I figured out that problem is in `django_redis.client.default.DefaultClient` method `incr_version`:
```python
try:
    ttl = client.ttl(old_key)
except _main_exceptions as e:
    raise ConnectionInterrupted(connection=client) from e
```

When we get ttl of the current key, redis client returns `-1`. After that, when client trying to set this ttl to the new key, it disappear immediately, because for infinite timeout we need to set `ttl=None`.

I guess, it can be fixed with following:
```python
ttl = client.ttl(old_key)
if ttl == -1:
    ttl = None
```

**Comment by WisdomPill** [comment]
Hello @z0ng33 ,

I did not understand what are you saying?

Do you have any code snippet or unittest to prove what are you saying?
It would be very helpful.

Thanks!

**Comment by z0ng33** [comment]
@WisdomPill It's example from django documentation:
```python
from django.core.cache import cache

cache.set('my_key', 'hello world!')
# redis:
# localhost:6379> keys *
# 1) ":1:my_key"

cache.incr_version('my_key')
# redis:
# localhost:6379> keys *
# (empty array)
#
# expected:
# 1) ":2:my_key"
```
