### ISSUE TITLE
cache.delete returns an integer instead of a boolean

### ISSUE THREAD

**Issue by saschametz** [jazzband/django-redis#486]
Hello, thanks for providing this great package.

I've just seen in the Django documentation (Version 3.1.) that the `cache.delete` API returns a boolean value [since version 3.1](https://docs.djangoproject.com/en/3.1/topics/cache/#django.core.caches.cache.delete):

<img width="865" alt="Screenshot 2020-12-11 at 08 51 41" src="https://user-images.githubusercontent.com/37977643/101877312-180f9000-3b8e-11eb-9f54-8c3dd8a749b1.png">

When I delete a cache key using the django-redis package it returns an integer instead of a boolean. Is this something that should be changed?

**Example:**
Using one of the built-in cache backends from Django:
```python
cache.delete("foobar")
>>> True
```

Using the django-redis package:
```python
cache.delete("foobar")
>>> 1
```

**Comment by WisdomPill** [comment]
Hello @saschametz, yes it should be changed, but imho it should change only from django 3.1 onwards.

A version check of django is very simple to do.

Do you fancy coming up with a PR to fix this?

**Comment by saschametz** [comment]
Hi @WisdomPill thanks for the answer. Sure, I'll take a look at it this weekend.

**Comment by pinoatrome** [comment]
HI all,
I've submitted a PR to help solve this issue.
It is my first submission to this great project, please let me know if it doesn't follow the code of conduct and/or anything has to be amended.
HTH
GG
