### ISSUE TITLE
Missing documentation for django-redis

### ISSUE THREAD

**Issue by sunilale0** [jazzband/django-redis#487]
Hi, I visited the following site:
https://readthedocs.org/projects/django-redis/

which links the django-redis documentation sites to https://django-redis.readthedocs.io/en/latest/ and https://django-redis.readthedocs.io/en/stable/ , both of which return an empty site. I was wondering if I am visiting the wrong link or if there is some other errors due to which documentation is missing.

I did find a pd version of the documentation though at https://readthedocs.org/projects/django-redis-chs/downloads/pdf/latest/.

**Comment by WisdomPill** [comment]
Hello @sunilale0!
Sorry for being late you can read the documentation on the README

**Comment by sunilale0** [comment]
@WisdomPill Thank you.
