### ISSUE TITLE
cache.keys('*') doesn't return template fragments

### ISSUE THREAD

**Issue by pgcd** [jazzband/django-redis#498]
I was trying to selectively invalidate some fragments on an AWS Elasticache database, and ended up against massive timeouts in `delete_pattern()`, so I tried from django shell and no `'template.cache*'` keys show up with `cache.keys('template*')`. 
To confirm, I checked with redis-cli, and `KEYS 'template*'` returns all the expected keys which, interestingly enough, seem to be used by the template caching system (at least, that's what the response time suggests).

Any ideas? Am I doing something wrong?

**Comment by pgcd** [comment]
Update: looks like this problem is caused by #382 - I'll investigate further.

**Comment by WisdomPill** [comment]
Hello @pgcd can you provide a code sample?

Can you also explain more in detail what numbers are talking about, how many keys are we talking about? 
Have you thought about using a large `COUNT` number?

Have you tried using plain `redis.Redis` client?

**Comment by pgcd** [comment]
I investigated a bit more and it turns out the problem is very likely caused by my setup - it's a cobbled-together multi-tenant thing, so it looks like the KEY_PREFIX is not set correctly in certain cases, which would explain why the keys are not found. 
As far as I can tell, the KEY_FUNCTION is used as expected, so please feel free to close the issue.
