### ISSUE TITLE
`incr` bug - deletes key when timeout is None if `client.eval` errors

### ISSUE THREAD

**Issue by AceFire6** [jazzband/django-redis#499]
I have a Django project set up with my cache config as follows:

```python
CACHES = {
    'default': {
        'BACKEND': 'django_redis_sentinel.cache.RedisSentinelCache',
        'LOCATION': [
            (REDIS_SENTINEL_SERVICE_URL, REDIS_SENTINEL_PORT),
        ],
        'TIMEOUT': REDIS_CACHE_TIMEOUT,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis_sentinel.client.SentinelClient',
            'SENTINEL_SERVICE_NAME': REDIS_SENTINEL_SERVICE_NAME,
            'REDIS_CLIENT_KWARGS': {
                'db': REDIS_DATABASE,
                'decode_responses': True,
            },
            'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
            'MAX_ENTRIES': REDIS_CACHE_MAX_ENTRIES,
        },
    },
}
```

We noticed weird behaviour in a case where we were calling `cache.incr(KEY, float_value)`

The keys were being created with a `TTL` of `0`.

Testing locally, I believe I've found the error. In `DefaultClient._incr`: 
https://github.com/jazzband/django-redis/blob/92896088479cb6710fb410307adb66d27dc9e058/django_redis/client/default.py#L408-L451

Specifically in this section of that code:
https://github.com/jazzband/django-redis/blob/92896088479cb6710fb410307adb66d27dc9e058/django_redis/client/default.py#L433-L447

When the `timeout` value is retrieved `django-redis` uses `client.ttl`. This ignores all the post-processing done in `DefaultClient.ttl`.

`client.ttl` in the case of the `None` timeout (we never want our keys to timeout by default) returns `-1`. In the call to `DefaultClient.set` that results when an error occurs (see above) `timeout` is set to `-1` and as can be seen in the following snippet. The key is deleted when `timeout` is negative and `nx` is not `True`:

https://github.com/jazzband/django-redis/blob/92896088479cb6710fb410307adb66d27dc9e058/django_redis/client/default.py#L139-L153

The simplest solution I've found in my testing is to call `self.ttl` instead of `client.ttl`

**Comment by WisdomPill** [comment]
Hello @AceFire6 thanks for pointing out this issue.

Would you be entered in making a PR to fix this?

**Comment by annbgn** [comment]
it's been a month since last update, so I took the issue and made a pr

**Comment by WisdomPill** [comment]
Thanks @annbgn I already left a review
