### ISSUE TITLE
typeerror: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by EquatorSavage** [jazzband/django-redis#500]
typeerror: a bytes-like object is required, not 'str'
```
from django_redis import get_redis_connection
conn_redis = get_redis_connection("default")
result = conn_redis.hgetall("*****")
Mac OS:  the type of result's key and value is bytes 
Win 7   :  the type of result's key and value is str
```

why?

**Comment by WisdomPill** [comment]
Can you provide your settings? I personally do not use windows since a long time, probably decoding is missing. Also I do not even know if windows is supported, I remember that in past version you could provide a deserialize/decode configuration, have you checked the versions you are running?

**Comment by WisdomPill** [comment]
@EquatorSavage a month has passed since the last reply, if no reply is given within a week or two I will take the issue as solved and close it
