### ISSUE TITLE
touch method converting seconds to milliseconds and then using pexpire instead of expire.

### ISSUE THREAD

**Issue by abbasidaniyal** [jazzband/django-redis#505]
https://github.com/jazzband/django-redis/blob/afb00223729d5caafa8b63f3684532aaa63f1963/django_redis/client/default.py#L604-L606

My suggestions : 
```
  def touch(self, key, timeout=DEFAULT_TIMEOUT, version=None, client=None):
        ...
        if timeout is None:
            return bool(client.persist(key))
        else:
            return bool(client.expire(key, timeout))
```

**Comment by WisdomPill** [comment]
Hello @abbasidaniyal,

sorry but I am not convinced it is a good idea, first and foremost because it would be a breaking change and also because `django` uses timeout in seconds, so it would be counter intuitive. you could use a `float` for example `1.234` seconds to it will be `1234` milliseconds and it would work.

Let me know if i answered your question, otherwise I will close the issue in a week or so

**Comment by abbasidaniyal** [comment]
Sure I get your point that it'll be a breaking change. However, 
https://github.com/jazzband/django-redis/blob/afb00223729d5caafa8b63f3684532aaa63f1963/django_redis/client/default.py#L243-L251

The `expire` method uses expire method os the client with timeout is seconds. I believe checking for float should be a validation problem. The value of timeout could be `1.2345` and this would still break. If the goal is to provide the user flexibility upto a millisecond (which I personally don't think is of much use), in that case we should modify the `expire` method and use pexpire. 

Let me know how you feel about this! 😃

**Comment by WisdomPill** [comment]
agree, so just line 250 would change and a multiplication by a thousand is needed so that you can pass a float?

**Comment by abbasidaniyal** [comment]
Sure, I think it'll be more consistant. 
However, still my first preference would still be using seconds as the unit of time and client.expire method to update the timeout. But I guess that would require some discussion among the maintainers first. 

Would be more than happy to take this issue up, irrespective of which approach is taken!

**Comment by WisdomPill** [comment]
how can you use `client.expire` and be precise to the millisecond?

**Comment by abbasidaniyal** [comment]
> how can you use `client.expire` and be precise to the millisecond?

We can't. I just think providing precision upto milliseconds is not really necessary in a real world scenario. This is just what I feel personally and from what I've seen in projects (mostly in the comapny that I worked in) where django-redis was used.

**Comment by WisdomPill** [comment]
I think they can both use `pexpire` for more precision if needed. I personally do not see the reason to use it, but if somebody would want to expire a key after half a second it would be handy to give the ability to do it. Also because it comes "for free" without breaking changes

**Comment by WisdomPill** [comment]
It seems related to #333 do you fancy stepping in and proposing a PR for that?

**Comment by abbasidaniyal** [comment]
> It seems related to #333 do you fancy stepping in and proposing a PR for that?

Yes I believe so too! Sure I'd like to take this up. Could you assign me the issue?
