### ISSUE TITLE
get Error 111 connecting to redis-prod:6380. Connection refused. 

### ISSUE THREAD

**Issue by HoudaMallem** [jazzband/django-redis#507]
I am using docker with docker-compose to deploy a Django app with Redis as a cache server 
it works perfectly with default Redis port = 6379 
once I change it I got this error 
Error 111 connecting to redis-prod:6380. Connection refused. 

my docker-compose file looks like 

```
version: '3'
services:
  db-prod:
    container_name: db-prod
    image: postgres
    volumes:
      - ./postgres-data-prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web-prod:
    container_name: web-prod
    environment:
     - ENV=prod
     - DEBUG=False
     - DB=db-prod
     - CACHE=redis-prod:6380
    build: .
    command: gunicorn -b 0.0.0.0:9001 web.wsgi:application --workers=10 --timeout=300
    volumes:
      - .:/code
    ports:
      - "9001:9001"
    depends_on:
      - db-prod
      - redis-prod
    links:
      - redis-prod
  redis-prod:
    image: redis
    container_name: redis-prod
    command: >
      --maxmemory 40g
    ports:
      - "6380:6379"
```

**Comment by WisdomPill** [comment]
Hello @HoudaMallem this issue is not related to the library, most probably to your docker setup, therefore I am closing it.

I invite you to use other tools such as stackoverflow for this kind of issue.
I also suggest to put your settings there.
