### ISSUE TITLE
Fix codecov

### ISSUE THREAD

**Issue by WisdomPill** [jazzband/django-redis#510]
Just have a look at the readme, there is the codecov badge but the tests are not setup for coverage

**Comment by krishp058** [comment]
But what specifically do you want me to do?

**Comment by WisdomPill** [comment]
Codecov does not get coverage sent to it after the tests, as a matter of fact if I remember correctly coverage does not even run. Let's close #506 first and then you could work on it so that we do not step on each other foot

**Comment by WisdomPill** [comment]
Basically we need to switch to pytest and use pytest-cov.

It could be difficult, probably it is not a "good first issue", @krishp058 do you still want to give it a try or I could step in and fix it.

[Here](https://github.com/codecov/codecov-action#example-workflowyml-with-codecov-action) is the "tutorial" by codecov.

**Comment by krishp058** [comment]
Oh sorry about the late response, I think it should be best if you can do this because I'm not very well familiar with codecov and also I'm still a beginner so I was looking from something that would match my skillset. But I really appreciate you trying to give me a chance. 

Thanks

**Comment by WisdomPill** [comment]
@terencehonles let's talk coverage and whether to switch to pytest or not.

I have tried locally to use coverage.py it seems to work, but I don't know how to make it work with tox.
Another thing is that the tests are launched separately so code coverage will not hit some clients or serializers in now run as of now.

Do you have any proposals, I remember you talked about switching to pytest previously

**Comment by terencehonles** [comment]
I think I figured out what we need to do to cover it all. I'll take care of this.

My current thoughts: Instead of creating N test runners with different settings use pytest and one runner and use fixtures to stub out the different CACHES.

**Comment by terencehonles** [comment]
Sadly I had forgotten that the fixture parametrization I was thinking to use would not work with unittest style test cases. We'll probably want to migrate off of those, but for now running pytest multiple times and appending to the coverage file should be fine.

**Comment by WisdomPill** [comment]
Do you want to create an issue for that?

Do you think it will be an easy issue for the people that want to help?

**Comment by terencehonles** [comment]
Yeah, I'll create an issue for it and see if anyone is willing to bite

**Comment by WisdomPill** [comment]
Thanks, if you can, also provide an example it would be easier for less skilled people.
