### ISSUE TITLE
Tests README

### ISSUE THREAD

**Issue by WisdomPill** [jazzband/django-redis#514]
README in tests is a txt file, GitHub does not format it, maybe it should me a rst file?

What do you think @terencehonles

**Comment by terencehonles** [comment]
Oh wow, I didn't even realize that when I updated it 😅. Yeah it should be changed.

**Comment by WisdomPill** [comment]
I guess it is a good first issue maybe for @krishp058 that wanted to help.

Basically it has to be changed to an rst file

**Comment by WisdomPill** [comment]
Sorry @krishp058, it was taken. Next time do you want me to assign to you some good first issue?
