### ISSUE TITLE
Add unix socket tests to CI

### ISSUE THREAD

**Issue by WisdomPill** [jazzband/django-redis#515]
CI is missing unix socket tests

**Comment by WisdomPill** [comment]
@terencehonles I guess we could add another instance of redis in [start_redis.sh script](https://github.com/jazzband/django-redis/blob/master/tests/start_redis.sh) to start an instance using unix sockets.

Am I right?

In case, I would be glad to take on the issue

**Comment by terencehonles** [comment]
No, I actually had fixed this with #506 and now we don't use a service definition and do the same thing as the test README suggests.

**Comment by terencehonles** [comment]
Thanks for making sure this didn't get dropped!
