### ISSUE TITLE
Tests are failing in django master

### ISSUE THREAD

**Issue by WisdomPill** [jazzband/django-redis#532]
Tests are failing for django master, can be seen in #531

**Comment by WisdomPill** [comment]
Seems to be related to `tox`, @terencehonles do you have any idea on how to solve it?

**Comment by neumantm** [comment]
Could
`django.utils.deprecation.RemovedInDjango50Warning: The default value of USE_TZ will change from False to True in Django 5.0. Set USE_TZ to False in your project settings if you want to keep the current default behavior.`
be the cause?

**Comment by WisdomPill** [comment]
No, that's a warning there is also an `InvocationError` probably from `tox`

**Comment by terencehonles** [comment]
The invocation error comes because the underlying command failed. It's the USE_TZ that's the underlying issue. I created #533 to fix the issue.
