### ISSUE TITLE
SRANDMEMBER support

### ISSUE THREAD

**Issue by okapies** [jazzband/django-redis#549]
**Problem Statement**
It seems `SRANDMEMBER` is not supported.

https://redis.io/commands/srandmember

**Describe the solution you'd like**
Add a feature to access `SRANDMEMBER`. `redis-py` (underlying implementation of `django-redis`) already has a support for it.

**Comment by WisdomPill** [comment]
Hello @okapies,

sets are not supported, if we need to support `SRANDMEMBER` then we will need to support all the other methods interacting with sets.

My opinion is that you should use a redis connection instead of django cache or create your own client that supports sets.

**Comment by WisdomPill** [comment]
closing as it is invalid.
