### ISSUE TITLE
Is TIMEOUT setting respected by django-redis?

### ISSUE THREAD

**Issue by honi** [jazzband/django-redis#56]
Hello, can anybody confirm that TIMEOUT setting is respected by django-redis? This is my configuration (I want key/values to _never_ expire):

```
CACHES = {
    'default': {
        'BACKEND': 'redis_cache.cache.RedisCache',
        'LOCATION': '127.0.0.1:6379',
        'KEY_PREFIX': 'my-prefix',
        'OPTIONS': {
            'TIMEOUT': None
        }
    }
}
```

**Comment by schumannd** [comment]
Any pointers how or where to solve this problem?

**Comment by peterstory** [comment]
@schumannd I initially thought there was a problem with django-redis because I was observing cache entries which weren't expiring. Actually, the problem was with Django Rest Framework: it uses its own setting for TIMEOUT. 
https://github.com/chibisov/drf-extensions/blob/master/docs/index.md#timeout

**Comment by schumannd** [comment]
@peterstory you linked a document for drf-extensions, which we don't explicitly use. We now set
`CACHE_MIDDLEWARE_SECONDS` to a very high value, as setting

```

CACHES = {
    "default": {
        "TIMEOUT": None,
        ...
```

does not seem to work.

**Comment by peterstory** [comment]
My goal was to have things time out after one day, so my settings look like this:

```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "TIMEOUT": 60 * 60 * 24, # Items in the cache will expire after 1 day
    }
}

REST_FRAMEWORK_EXTENSIONS = {
    'DEFAULT_CACHE_RESPONSE_TIMEOUT': 60 * 60 * 24, # 1 day timeout, as above
}
```

I have not tried setting `"TIMEOUT"` to None, so unfortunately I cannot comment on whether it works or not.

**Comment by schumannd** [comment]
@peterstory but are you using drf-extensions in any way or does this setting also work when only using drf?

**Comment by peterstory** [comment]
I am using:
```
djangorestframework==3.3.0
drf-extensions==0.3.1
```

**Comment by Elendiar** [comment]
When you use middleware `django.middleware.cache.UpdateCacheMiddleware` it is `self.cache_timeout = settings.CACHE_MIDDLEWARE_SECONDS` in it, so you can set timeout using global variable `CACHE_MIDDLEWARE_SECONDS` in settings

**Comment by DominiqLesniak** [comment]
I've noticed, that correct sequence of the CACHES dict items makes a difference : 

previous : 

```
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": f"redis://redis",
            "TIMEOUT": 900,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient"
            }
        }
    }
```


present (positively tested) : 


```
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": f"redis://redis",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient"
            },
            "TIMEOUT": 900
        }
    }

```
