### ISSUE TITLE
Roadmap for next release

### ISSUE THREAD

**Issue by WisdomPill** [jazzband/django-redis#562]
There are a few new things for the next release already.

Can we discuss on what is blocking the next release? Maybe call it even 5.1.0

I would say to solve the problem with redis-py>=4.0.0 is the only blocker

@terencehonles what do you think?

**Comment by WisdomPill** [comment]
Agree.

I would like to finish sorting out the return value of `pexpire`, `expire`, `expire_at` and `pexpire_at`.

Seems like the return value is missing, let's wait for #565 then we can release `5.1.0`

**Comment by WisdomPill** [comment]
Hello @terencehonles,

I have some issues reproducing and solving the issue of sentinel disconnection.

I guess I need to learn better on how to use tox and redis sentinel.

@terencehonles can you have a look at the issue? 
Or we can just limit the `redis-py` dependency for `redis-py<4` as you suggested previously and try to make our first "independent" release.

**Comment by terencehonles** [comment]
@WisdomPill I'm not sure I'm following your first part about tox and redis sentinel. If you're just wondering how to start both you can use `./tests/start_redis.sh; ./tests/start_redis.sh --sentinel` and at that point you should be able to use tox just like the CI does. I'll poke at the tests to see if it's trivial to support redis-py 4.x since it's in RC now and hopefully won't change too much.

**Comment by WisdomPill** [comment]
I did use your scripts, with some light change because I am on macOS, I managed to run redis and redis sentinel but still did not manage to run tox without lots of errors, I did not spend mush time on it.

**Comment by terencehonles** [comment]
I looked into this for quite awhile and it looks like this needs a pretty large re-working. The sentinel config will need make sure it's using the right connection pool and sentinel for the changes in redis-py. I'll create an issue for this, but we should probably just release with redis<4 for now.

**Comment by terencehonles** [comment]
@WisdomPill I think we probably should cut the release since it looks like redis 4 is already out. Was there anything else you wanted to include? Did you want to do it or do you want me to push to jazzband?

**Comment by WisdomPill** [comment]
I personally do not understand how the publishing works.

I would be happy to learn, if `redis<4` is pinned we can release of sure.

**Comment by terencehonles** [comment]
@WisdomPill yup, it's pinned. You should be able to follow https://github.com/jazzband/django-redis/blob/master/RELEASING.rst for what I believe should happen.

**Comment by WisdomPill** [comment]
Okay, I could try, I don't really get the step 5, should I have PyPi access for it?

**Comment by terencehonles** [comment]
You would upload it through jazzband which is what I had linked to right before the pypi comment since you're doing that, but via the previous link.

**Comment by Mogost** [comment]
Could someone release a new version with a pinned version of redis-py?
Every day without this release, someone can install incompatible versions.

**Comment by WisdomPill** [comment]
yep, it is in my plans to do so, I will do this weekend I guess

**Comment by Mogost** [comment]
@WisdomPill There is any updates?

**Comment by WisdomPill** [comment]
@Mogost I am really sorry, I completely forgot about it and been busy with other personal projects this weekend.

I prepared the release, and you can see it in the mentioned PR.

**Comment by WisdomPill** [comment]
Released
