### ISSUE TITLE
Support redis-py 4.0

### ISSUE THREAD

**Issue by terencehonles** [jazzband/django-redis#569]
**Problem Statement**

The [Redis Python client is now in RC1](https://github.com/redis/redis-py/releases/tag/v4.0.0rc1) but introduces some breaking changes (specifically seen with the Sentinel configuration). This library should be updated to support the new changes ideally in a backwards compatiable manner.

**Comment by WisdomPill** [comment]
there is already an issue for this, it is #542

**Comment by terencehonles** [comment]
Well I think they're related, but is this the only thing that's broken in redis 4?

**Comment by hartwork** [comment]
CC #575 #576

**Comment by aleehedl** [comment]
Is there any estimate when this will be available in a release?

**Comment by WisdomPill** [comment]
I can release in the next days, max Monday. 

Can I ask why you are looking for redis-py 4 as a dependency?

**Comment by WisdomPill** [comment]
I would wait for #580 to be merged and then release

**Comment by aleehedl** [comment]
> Can I ask why you are looking for redis-py 4 as a dependency?

Yeah, because redis-py 4 was already installed into a production system and I'm not sure how a downgrade would pan out.

**Comment by WisdomPill** [comment]
I can say that the only known issue is with sentinel commands that are different in 4.0.1 and 4.0.2, the rest of the versions are supported, I am waiting for @terencehonles to review #580 to support django 4 and drop support for django 2.2

**Comment by WisdomPill** [comment]
Will release tomorrow
