### ISSUE TITLE
Default client does not pass `blocking` kwarg through lock method

### ISSUE THREAD

**Issue by thenewguy** [jazzband/django-redis#596]
Traceback:
```
    lock = cache_redis_lock.lock(name, blocking=False, timeout=240)
  File "/home/vagrant/.tox/py37/lib/python3.7/site-packages/django_redis/cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
  File "/home/vagrant/.tox/py37/lib/python3.7/site-packages/django_redis/cache.py", line 173, in lock
    return self.client.lock(*args, **kwargs)
TypeError: lock() got an unexpected keyword argument 'blocking'
```

This should be an acceptable kwarg per https://github.com/redis/redis-py/blob/3.5.3/redis/lock.py#L74 and the threading.Lock implementation.

It is not listed in the `lock` signature on the default client at https://github.com/jazzband/django-redis/blob/5.0.0/django_redis/client/default.py#L329

**Comment by WisdomPill** [comment]
That is a `redis-py` [issue](https://github.com/redis/redis-py/issues/1348) which should be taken care of there.

**Comment by thenewguy** [comment]
@WisdomPill ^

**Comment by thenewguy** [comment]
`DefaultClient.lock` does not accept **kwargs and does not list `blocking` as an argument it accepts in the signature

**Comment by WisdomPill** [comment]
sorry, I thought you were using lock as context manager

**Comment by WisdomPill** [comment]
I would add `*args` and `**kwargs` to that function, would you be up for a PR?

**Comment by WisdomPill** [comment]
Actually

**Comment by WisdomPill** [comment]
I would suggest to open an issue and maybe a PR in `redis-py` first and then make changes to `django-redis`, otherwise the desired behavior is not possible.

**Comment by WisdomPill** [comment]
Hello @AqeelAT,

I actually made the pr not long ago to be able to proceed with #603 in redis/redis-py#2137 :)
But unfortunately I did not get back to #603 just yet

**Comment by AqeelAT** [comment]
Oh I just noticed that you're the one who made https://github.com/redis/redis-py/pull/2137.
We could definitely benefit from #603 
I think it is ready to be merged.

**Comment by WisdomPill** [comment]
Done, sorry for the long time needed
