### ISSUE TITLE
Add exception info to logger message when exceptions are ignored

### ISSUE THREAD

**Issue by tmarice** [jazzband/django-redis#611]
We're using django-redis as a session cache backend for our Django project, with DJANGO_REDIS_IGNORE_EXCEPTIONS and DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS set to True. 

Unfortunately, we're experiencing a pesky Redis TimeoutError, which due to the previous settings, is only getting logged as:
```
ERROR    django_redis.cache 2022-06-08 17:16:54,470 cache.py _decorator 35 Redis TimeoutError: Timeout reading from socket
```

The issue happens only in the production environment, and we can't get a full exception traceback without impacting customers, so debugging this has been difficult. We'll probably work around this by live-editing the cache module on the web servers.

What are your thoughts on using `self.logger.exception` instead of `self.logger.error` in the [omit_exception decorator](https://github.com/jazzband/django-redis/blob/master/django_redis/cache.py#L35), or adding another setting (e.g. `DJANGO_REDIS_LOG_EXCEPTION_TRACEBACK`) which would control the logging behavior?

**Comment by WisdomPill** [comment]
Hello @tmarice, 
yes that's perfectly fine by me, 
I prefer using `log.exception` instead of `log.error` but since I inherited this project I did not touched that. 

You are welcome to open a PR.

If I may give you an advice to use a tracing system, like `Sentry` and you would never have this problem again :)

**Comment by tmarice** [comment]
Excellent, I'll try to free up some time in the following weeks to work on this.

Unfortunately, Sentry doesn't help here since the exception is caught and logged. Sentry picks it up from the logger, but it's missing local variables and the full traceback.
