### ISSUE TITLE
Why does `DJANGO_REDIS_CONNECTION_FACTORY` need to be a global django setting ?

### ISSUE THREAD

**Issue by vedantpuri** [jazzband/django-redis#619]
## Context
We use django-redis for our project and I am in a situation where I need to make only one of my caches sentineled.
Ideally the others should also be converted but due to time constraints and other reasoning based on usage we want to convert only one for now. 

## Question
When trying to change this I noticed that this setting is global, which means that all my caches need to be sentineled for this to work. I am not exactly sure why this is global and/or if this could be moved into OPTIONS per cache to provide more flexibility.

**Comment by WisdomPill** [comment]
Hello @vedantpuri,

I see your issue, I think it's a valid point so we should have a pool per `cache` entry in settings... would you like to create a PR for this?

It should be quite simple, just pass `CONNECTION_FACTORY` from options and feed it to `pool.get_connection_factory(options=self._options)` [here](https://github.com/jazzband/django-redis/blob/38e630f051d6cc1f54e2e919c5751853282657ee/django_redis/client/default.py#L62) as path and the trick is done.

If you do it yourself I would be glad to review and release a new version pretty quickly.

**Comment by vedantpuri** [comment]
Sure! Here is a proposal:
https://github.com/jazzband/django-redis/pull/620

**Comment by RealFatCat** [comment]
@WisdomPill hi, can you look at https://github.com/jazzband/django-redis/pull/680 please?

**Comment by RealFatCat** [comment]
@WisdomPill can we get a release with this feature?

**Comment by WisdomPill** [comment]
I released it yesterday, thanks @RealFatCat for the PR! 😄
