### ISSUE TITLE
redis DB flushed on "django restart", how can I stop this?

### ISSUE THREAD

**Issue by jamiegau** [jazzband/django-redis#628]
Hi,
I have set up Redis to write to disk its DB so it can persist its data over a restart.

However, when I stop/start my Django container. Everything in the Redis database, for example, /1 is deleted.
How can I stop this from happening?  I have not been able to find any reference to this behaviour on github or in the issues tracker.

I would expect an OPTION could be set to disable this behaviour?

Would appreciate some feedback on this issue.
Thanks,

**Comment by WisdomPill** [comment]
I don't get how, it's the first time I hear about such a problem.

Can you explain more in. detail how is your setup?
How is redis setup, what are your settings and how are you using `django_redis`?

Do you have any logs from redis server that prove there was a flush command sent?

**Comment by jamiegau** [comment]
Thanks for confirming this should work.
It made me look in other places, and I found a flush cache in the celery worker start process in my IDE.
THANKS.
