### ISSUE TITLE
Django unit tests hang forever when redis is not reachable

### ISSUE THREAD

**Issue by awbacker** [jazzband/django-redis#630]
When my redis instance is not reachable, it seems that my unit tests hang indefinitely.  No single test is executed, though, just a hang after the system checks.

I have tried setting the timeouts, socket timeouts, etc, without any luck.  

Is there some way to get this to fail faster, is there something I am configuring incorrectly? 

```
project ❯ ./manage.py test
Found 262 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
# <hangs here>
# ^C^C to exit
```

```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/1",
        "TIMEOUT": 5,
        "OPTIONS": {
            "SOCKET_TIMEOUT": 5,
            "SOCKET_CONNECT_TIMEOUT": 5
        }
    }
}

**Comment by awbacker** [comment]
Not sure how you tracked yours down, but so far mine doesn't seem the same.  I stuck a couple `print()`s around there and saw nothing.  

Maybe I've posted this in the wrong place. At the time I thought it was right, though, but now it seems like I have even less clue.  RQ? core redis?

In my case it doesn't even seem to start the testing, and the stack trace when I kill the process is always stuck here:

```
python3.11/site-packages/rq/job.py", line 696, in save
    if self.get_redis_server_version() >= (4, 0, 0):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
python3.11/site-packages/rq/utils.py", line 281, in get_version
    return tuple(int(i) for i in connection.info("server")["redis_version"].split('.')[:3])
...
python3.11/site-packages//rq_scheduler/scheduler.py", line 246, in schedule
    job.save()
...
python3.11/site-packages/redis/connection.py", line 734, in on_connect
    if str_if_bytes(self.read_response()) != "OK":
                    ^^^^^^^^^^^^^^^^^^^^
...
python3.11/site-packages/redis/connection.py", line 318, in read_response
    raw = self._buffer.readline()
          ^^^^^^^^^^^^^^^^^^^^^^^
python3.11/site-packages/redis/connection.py", line 249, in readline
    self._read_from_socket()
python3.11/site-packages/redis/connection.py", line 192, in _read_from_socket
    data = self._sock.recv(socket_read_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by adamkal** [comment]
Indeed, I definitely get an connection exception that goes further into tests and get's stuck later, when collecting traceback.

Might be worth mentioning I'm working on Python 3.9

**Comment by awbacker** [comment]
My tone comes off way wrong on that one, what I meant was:  "I don't know how you tracked that down, amazing work.  I read the code and didn't see anything wrong, hats off to you!"

I was thinking the same thing re: versions, and am going to try again with py3.10 and see if it shows up the same.

**Comment by awbacker** [comment]
This issue is not the result of django-redis, as far as I can tell.  Reopen if you find a link.

**Comment by awbacker** [comment]
> I have the same issue. I found an infinite loop in the [`TestCase._clean_tracebacks`](https://github.com/python/cpython/blob/044fb4fb53594b37de8188cb36f3ba33ce2d617e/Lib/unittest/result.py#L194)
> 
> In my case this is the way `excs` changes with each loop:
> 
> ```
> [(<class 'redis.exceptions.ConnectionError'>, ConnectionError('Error 111 connecting to localhost:6379. Connection refused.'), <traceback object at 0x7f064a03f700>)]
> [(<class 'django_redis.exceptions.ConnectionInterrupted'>, ConnectionInterrupted(), <traceback object at 0x7f0649e8fa00>)]
> [(<class 'redis.exceptions.ConnectionError'>, ConnectionError('Error 111 connecting to localhost:6379. Connection refused.'), <traceback object at 0x7f064a03f700>)]
> [(<class 'django_redis.exceptions.ConnectionInterrupted'>, ConnectionInterrupted(), <traceback object at 0x7f0649e8fa00>)]
> ```
> 
> Seems to me that the problem is in [this line in `omit_exception`](https://github.com/jazzband/django-redis/blob/9d572cd460e1acc0458dfa32a5137eb55b844c52/django_redis/cache.py#L38).
> 
> I noticed that the algorithm for cleaning is [fairly fresh](https://github.com/python/cpython/pull/31776) which might be the trigger of the issue

I see this now, but when NOT using rq/scheduling and just standard using standard redis!  This is definitely a thing!  Wow.
