### ISSUE TITLE
Python 3.6 and tox>4 are incompatible

### ISSUE THREAD

**Issue by iurisilvio** [jazzband/django-redis#645]
**Describe the bug**

* Python 3.6 reached EOL and Ubuntu 22.04 doesn´t support it.
* Tox 4 changed `passenv` config, now it is a comma separated value.
* Tox 4 dropped support to Python 3.6.

It is possible to run tests with Python 3.6 and `tox<4` in Ubuntu 20.04 or drop Python 3.6 to run latest tox and Ubuntu 22.04.

Related to #642.

**Comment by iurisilvio** [comment]
I prefer drop EOL version, but did both solutions here.

Drop Python 3.6 support: https://github.com/jazzband/django-redis/pull/644
Maintain Python 3.6 support. https://github.com/jazzband/django-redis/pull/643

**Comment by WisdomPill** [comment]
I would prefer to drop django 2.2 and django 3.1 but not python 3.6 because it is still supported in django 3.2

**Comment by WisdomPill** [comment]
also we need to add django 5 to CI... but maybe it's better to have a PR for removing old versions and one to add the new one

**Comment by iurisilvio** [comment]
Merged #643.
