### ISSUE TITLE
Are bulk methods still available ?

### ISSUE THREAD

**Issue by MarchesiGabriele** [jazzband/django-redis#652]
Hi, 
I'm trying to use the cache.keys() method since I want to retrieve a bunch of keys with the same pattern. In the documentation I found those methods:
![image](https://user-images.githubusercontent.com/66092080/213939945-7db75c7b-d2ae-421c-a9cb-8e1e5807958b.png)
but when I use them I get  " RedisCache object has no attribute 'keys' ". 
All those bulk methods dont even show up between the available methods in the autocomplete tool.
Is the documentation out of date ?
Is there another way, using the existing methods, to retrieve / delete in bulk ?

Thank you

**Comment by MarchesiGabriele** [comment]
I figured out the problem. 
I removed this line from the cache settings in the settings.py file and now it works correctly

**Comment by mihailkasev** [comment]
@MarchesiGabriele , I'm solving this kind of problem right now. 
Could you tell me, what line in cache settings in settings.py file did you remove? Thank you

**Comment by MarchesiGabriele** [comment]
I think it was something wrong in the cache configuration, I mixed up two different modules and I didnt notice. 
I'm now using
```
'BACKEND': 'redis_cache.RedisCache', 
``` 
instead of 
```
"BACKEND": "django_redis.cache.RedisCache",
``` 
The documentation is correct, it was my mistake.
