### ISSUE TITLE
patch delete like methods to use unlink api

### ISSUE THREAD

**Issue by yuchunzhou** [jazzband/django-redis#660]
The Redis server has a `lazyfree-lazy-user-del` feature, the server will run the `DEL` command as if running `UNLINK` command if this feature is on. Although user can config the redis server to enable the feature, but if user won't config it, the `UNLINK` is a better choice. I read the delete like methods code of `django-redis`, all of them just call `redis-py`'s delete api, why not call unlink api?

**Comment by WisdomPill** [comment]
I did not understand what are you talking about, could you elaborate more?

**Comment by yuchunzhou** [comment]
Ok.
The Redis server has a `lazyfree-lazy-user-del` feature, the server will turn the `DEL` command into `UNLINK` command if this feature is on, the `UNLINK` has a better performance than `DEL` command and it's nonblock.

**Comment by yuchunzhou** [comment]
the `django-redis` package's delete like methods call the redis-py's delete method directly, maybe we can patch these delete like methods to use redis-py's unlink method, the package's performance will be better when deleting somethings.

**Comment by yuchunzhou** [comment]
@WisdomPill you can get more information about `lazyfree-lazy-user-del` at this [https://stackoverflow.com/questions/45818371/is-the-unlink-command-always-better-than-del-command](page)

**Comment by WisdomPill** [comment]
now I get it, I think we might want to add a flag on delete methods... would you fancy opening a PR for it?

**Comment by yuchunzhou** [comment]
@WisdomPill yeah, maybe we should a config option to the OPTIONS dict and call the right delete method obey that config option, the decision is in users' hand, users choose the right delete method for different application situation.
