### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by foarsitter** [jazzband/django-redis#669]
69 commits ago there was a release. Isn't time for the next release? 

## What's Changed
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/jazzband/django-redis/pull/584
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/jazzband/django-redis/pull/586
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/jazzband/django-redis/pull/589
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/jazzband/django-redis/pull/592
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/jazzband/django-redis/pull/599
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/jazzband/django-redis/pull/605
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/jazzband/django-redis/pull/612
* #609, use pipeline for delete_pattern by @rootart in https://github.com/jazzband/django-redis/pull/617
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/jazzband/django-redis/pull/615
* update readme links by @Arhell in https://github.com/jazzband/django-redis/pull/622
* update AUTHORS links by @Arhell in https://github.com/jazzband/django-redis/pull/624
* Fix mypy errors by @foarsitter in https://github.com/jazzband/django-redis/pull/626
* Add Django 4.1 to test matrix and classifiers by @foarsitter in https://github.com/jazzband/django-redis/pull/627
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/jazzband/django-redis/pull/625
* Log traceback if exceptions are ignored by @tmarice in https://github.com/jazzband/django-redis/pull/613
* Fix CI, with Python 3.6 support. by @iurisilvio in https://github.com/jazzband/django-redis/pull/643
* Dropped support for django 2.2 and 3.1 by @WisdomPill in https://github.com/jazzband/django-redis/pull/648
* Added support for python 3.11 by @WisdomPill in https://github.com/jazzband/django-redis/pull/650
* #646, fix skip tests for the django.contrib.sessions.serializers.Pick… by @rootart in https://github.com/jazzband/django-redis/pull/647
* Fix 646 changelog and flake8 by @WisdomPill in https://github.com/jazzband/django-redis/pull/651
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/jazzband/django-redis/pull/632
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/jazzband/django-redis/pull/662
* Fix #638 Lazy access to Django settings. by @iurisilvio in https://github.com/jazzband/django-redis/pull/639
* Add Django 4.2 to test matrix and classifiers by @foarsitter in https://github.com/jazzband/django-redis/pull/668

## New Contributors
* @Arhell made their first contribution in https://github.com/jazzband/django-redis/pull/622
* @foarsitter made their first contribution in https://github.com/jazzband/django-redis/pull/626
* @tmarice made their first contribution in https://github.com/jazzband/django-redis/pull/613
* @iurisilvio made their first contribution in https://github.com/jazzband/django-redis/pull/643

**Full Changelog**: https://github.com/jazzband/django-redis/compare/5.2.0...master

**Comment by WisdomPill** [comment]
yeah, I was thinking to make a release for a while but kept forgetting... sorry about that, but now in my current company we started using more `django-redis` so I believe you will see updates soon, not only the release

**Comment by foarsitter** [comment]
As a jazzband member I can create a release isn't? It is the responsibility of the community and not yours alone but I'm looking forward to your updates!

**Comment by WisdomPill** [comment]
yes, you can, I can help you if you need guidance in case you need it

**Comment by foarsitter** [comment]
If you will review https://github.com/jazzband/django-redis/releases/edit/untagged-c616b0e698172823936a then we are good to go.

**Comment by WisdomPill** [comment]
sorry, but we don't do it like this, there is towncrier which creates the changelog, you will need to follow this [releasing guide](https://github.com/jazzband/django-redis/blob/master/RELEASING.rst) so that it will be published to pypi.

that said I would really love to see releases in GitHub and not only tags so feel free to add those too 😄

**Comment by foarsitter** [comment]
Hehe, hoped all would be fixed in the release action when creating a tag. Can you review #670 https://github.com/jazzband/django-redis/pull/670?
