### ISSUE TITLE
Is there a typo in  documentation?

### ISSUE THREAD

**Issue by the0s** [jazzband/django-redis#671]
Documentation for the itersize parameter of the delete_pattern says:
cache.delete_pattern("foo_*", itersize=100_000)

is 100_000 correct? shouldn't be 100000 ?

**Comment by WisdomPill** [comment]
it's plain python, try it and you'll see 😄

**Comment by the0s** [comment]
yeap called the function with 100_000 and 100000 and worked just fine for both but i am wondering why
as initializing a variable x=100_000 doesn't work. Is there anywhere i can read more about this?

**Comment by the0s** [comment]
yeap! First time seeing seeing this. Thanks
