### ISSUE TITLE
object attribute is missing after manager.py is restarted when using django redis cache

### ISSUE THREAD

**Issue by sinall** [jazzband/django-redis#682]
Here is the sample code:

```
class CrossSection(LoggerMixin):
    pass

class CrossSectionFactory(LoggerMixin):
    cross_section_sequence = {}

    def add(self, date):
        cross_section = CrossSection()
        self.cross_section_sequence[date] = cross_section

class Analyzer(LoggerMixin):
    cross_section_factory = None

    def __init__(self, logger=None, **kwargs):
        self.cross_section_factory = CrossSectionFactory(logger=logger, **kwargs)

    def init(self):
        pass

# ----
from django.core.cache import cache

class MyDetail(APIView):
    def post(self, request, analyzer_id, date, format=None):
        analyzer = cache.get("analyzer:1")
        if analyzer is None:
            analyzer = Analyzer(**{})
            analyzer.init()
        cache.set("analyzer:1", analyzer)
```

settings.py:

```
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://xxx:xxxxx@xxx.com:6379",
        "TIMEOUT": None,
    }
}
```
If the manger.py is not restarted, it can get analyzer with all attributes, but if manger.py restarts, the other attributes are all good except analyzer.cross_section_factory.cross_section_sequence, it become {} again.

I tried set/get the analyzer.cross_section_factory directly, it seems that works fine.

Do you know why this happens? How do I fix it?

====

Update: I changed the cache key, then I can set/get the analyzer now. It seems that the set operation didn't work properly, do you know why?

====

Update: I `delete` the key before `set` I can see that the key is deleted in redis (checked from redis-cli).  And I compared the value it is same as previous. So the problem I think is the serialization has some problem.

**Comment by WisdomPill** [comment]
hello @sinall, this is not the intended use of the library but most importantly you're using a class attribute and not an instance attribute, so actually `cross_section_sequence` is shared among all instances and initialised at declaration time (of `CrossSectionFactory`).

An example of what happens with class attributes is the following:

```
>>>class A:
...    b = {}
    
>>>A.b
{}
>>>a = A()
>>>a.b
{}
>>>A.b["a"] = "a"
>>> a.b
{'a': 'a'}
>>>class A:
...    b = {}
    
>>>a.b
{'a': 'a'}
>>>A.b
{}
```

so redeclaring `class A` overwrites class attributes. I would suggest you to cache only `cross_section_sequence` if you are interested in sharing that between processes/servers. I strongly discourage using pickle as it has security issues and is not that performant in big scale apps
