### ISSUE TITLE
Which timezone wil it take? system timezone or django timezone  

### ISSUE THREAD

**Issue by devanghingu** [jazzband/django-redis#714]
I am presently saving the `auth-token` from a third-party API in the django-Redis cache. 
how can i configure the different timezone? or how can i know which timezone django-redis is currently using?

**Comment by WisdomPill** [comment]
Hello, `django-redis` does not have any concept of timezone, your third party library should take care of that... the only time related concept in `django-redis` is the timeout which is in absolute terms except when using `expire_at`ethid which accepts timestamp and `datetime`, in such case `redis-py` will convert the `datetime` object in Unix timestamp using `.timestamp()`
