### ISSUE TITLE
Multiple redis caches with fallback mechanism

### ISSUE THREAD

**Issue by shekharskamble** [jazzband/django-redis#732]
Hello All,

new to the django and redis in general and tasked to work on redis upgrade (4.0 -> 7.0) and we use django-redis package. To have as less downtime as possible we are planning blue/green kind of set up where we will have 2 redis caches (old 4.0 & new 7.0) and then switch to 7.0 once the 4.0 cache is empty.

Going through the docs I see no fallback mechanism available in django-redis. I tried this package https://github.com/Kub-AT/django-cache-fallback but it doesn't work well with django-redis.

To all the package users and contributors, can you guide me on how can I achieve fallback to new redis cache?

Thanks

**Comment by WisdomPill** [comment]
Hello @shekharskamble, 

I wouldn't do make it so complicated and not even use a separate library, just deploy two versions at the same time and reroute traffic slowly. You might need to backfill your cache if it is needed. But it depends on your case I would search around the web on how to migrate with no downtime if your app really needs it. It's not always the case, and cache misses can be tolerated as they should not provoke downtime. 

I wouldn't ask such question in GitHub, probably stackoverflow is more suitable for these kind of issues.
